export const captions = {
    title: 'Create your profile',
    firstName: 'First Name',
    lastName: 'Last Name',
    displayName: 'Display Name',
    jobTitle: 'Job Title',
    organization: 'Organization',
    email: 'Email Address',
    emailMessage: 'Valid email is required',
    firstNameRequiredMessage: 'First Name is required',
    lastNameRequiredMessage: 'Last Name is required',
    specialCharacterErrorMessage: 'Invalid characters',
    fieldMessage: 'Content field is invalid',
    firstNamePlaceholder: 'Enter your First Name',
    lastNamePlaceholder: 'Enter your Last Name',
    displayNamePlaceholder: 'Enter a name you would like to be displayed',
    displayNameRequiredMessage: 'Display Name is required',
    jobTitlePlaceholder: 'Enter your Job Title',
    organizationPlaceholder: 'Enter your Organization',
    emailPlaceholder: 'Enter your Email',
    groupTitle: 'Group',
    roleDefault: 'Admin',
    buttonBack: 'Back',
    buttonNext: 'Next',
};
